[package]
name = "fish_fall"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = "0.25.0"
strum_macros = "0.25.1"
serde = { version = "1.0.174", features = ["derive"] }
bincode = "1.3.3"

[dependencies.fyrox]
workspace = true