[workspace]
members = ["editor", "executor", "game"]
resolver = "2"

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies.fyrox]
git = "https://github.com/FyroxEngine/Fyrox"
[workspace.dependencies.fyroxed_base]
git = "https://github.com/FyroxEngine/Fyrox"