[workspace]
members = ["editor", "executor", "game", "executor-wasm", "game-dylib"]
resolver = "2"

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies.fyrox]
path = "../Fyrox/fyrox"
[workspace.dependencies.fyroxed_base]
path = "../Fyrox/editor"
