[package]
name = "game_dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
fish_fall = { path = "../game", default-features = false }

[features]
default = ["fish_fall/default"]
dylib-engine = ["fish_fall/dylib-engine"]