[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
fish_fall = { path = "../game", optional = true }

[dependencies.fyroxed_base]
workspace = true

[features]
default = ["fish_fall", "fyroxed_base/default"]
dylib = ["fyroxed_base/dylib_engine"]