[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = { workspace = true }
fish_fall = { path = "../game", optional = true }

[features]
default = ["fish_fall"]
dylib = []